import Link from "next/link";
import { AdminShell } from "@/components/admin-shell";
import { createClient } from "@/lib/supabase/server";
import { defaultSettings, formatDate, getAboutPage, getProjectsPage, type Post, type Project, type ProjectsPage, type SiteSettings, type Skill } from "@/lib/data";
import { deletePost, deleteProject, deleteSkill, updateAboutPage, updateProjectsPage, updateSettings } from "@/app/admin/actions";

export default async function AdminPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const { saved, error } = await searchParams; const supabase = await createClient();
  const [{ data: posts }, { data: settings }, { data: projects }, { data: skills }, about, projectsPage] = await Promise.all([supabase.from("posts").select("*").order("updated_at", { ascending: false }), supabase.from("site_settings").select("*").eq("id", 1).maybeSingle(), supabase.from("projects").select("*").order("sort_order", { ascending: true }).order("created_at", { ascending: true }), supabase.from("skills").select("*").order("sort_order", { ascending: true }).order("created_at", { ascending: true }), getAboutPage(), getProjectsPage()]);
  const site = { ...defaultSettings, ...(settings as Partial<SiteSettings> | null) }; const notice = saved ? "Perubahan berhasil disimpan." : error ? "Perubahan belum berhasil disimpan. Pastikan migration terbaru sudah dijalankan." : "";
  return <AdminShell><div className="dashboard-stack">{notice && <div className={error ? "form-error" : "notice"}>{notice}</div>}
    <section><div className="admin-section-heading"><div><h2>Tulisan</h2><p>Kelola draft dan tulisan yang sudah diterbitkan.</p></div><Link className="button" href="/admin/posts/new">+ Tulisan baru</Link></div><div className="admin-card table-wrap">{posts?.length ? <table><thead><tr><th>Judul</th><th>Status</th><th>Diperbarui</th><th></th></tr></thead><tbody>{(posts as Post[]).map(post => <tr key={post.id}><td><strong>{post.title}</strong><small>{post.category}</small></td><td><span className={`status status-${post.status}`}>{post.status}</span></td><td>{formatDate(post.updated_at)}</td><td><div className="row-actions"><Link className="text-link" href={`/admin/posts/${post.id}`}>Edit</Link><form action={deletePost}><input type="hidden" name="id" value={post.id}/><button className="danger-link">Hapus</button></form></div></td></tr>)}</tbody></table> : <div className="empty-state"><p>Belum ada tulisan.</p></div>}</div></section>
    <section><div className="admin-section-heading"><div><h2>Projects & karya</h2><p>Tambah dan kelola karya yang tampil di halaman Projects.</p></div><Link className="button" href="/admin/projects/new">+ Project baru</Link></div><div className="admin-card table-wrap">{projects?.length ? <table><thead><tr><th>Project</th><th>Status</th><th>Urutan</th><th></th></tr></thead><tbody>{(projects as Project[]).map(project => <tr key={project.id}><td><strong>{project.title}</strong><small>{project.eyebrow}</small></td><td><span className={`status ${project.visible ? "status-published" : "status-draft"}`}>{project.visible ? "tampil" : "disembunyikan"}</span></td><td>{project.sort_order}</td><td><div className="row-actions"><Link className="text-link" href={`/admin/projects/${project.id}`}>Edit</Link><form action={deleteProject}><input type="hidden" name="id" value={project.id}/><button className="danger-link">Hapus</button></form></div></td></tr>)}</tbody></table> : <div className="empty-state"><p>Belum ada project.</p></div>}</div></section>
    <section><div className="admin-section-heading"><div><h2>Skill aplikasi</h2><p>Kelola aplikasi, logo, tingkat kemampuan, dan urutan di halaman About.</p></div><Link className="button" href="/admin/skills/new">+ Skill baru</Link></div><div className="admin-card table-wrap">{skills?.length ? <table><thead><tr><th>Aplikasi</th><th>Status</th><th>Urutan</th><th></th></tr></thead><tbody>{(skills as Skill[]).map(skill => <tr key={skill.id}><td><strong>{skill.name}</strong><small>{skill.level || "Tanpa keterangan"}</small></td><td><span className={`status ${skill.visible ? "status-published" : "status-draft"}`}>{skill.visible ? "tampil" : "disembunyikan"}</span></td><td>{skill.sort_order}</td><td><div className="row-actions"><Link className="text-link" href={`/admin/skills/${skill.id}`}>Edit</Link><form action={deleteSkill}><input type="hidden" name="id" value={skill.id}/><button className="danger-link">Hapus</button></form></div></td></tr>)}</tbody></table> : <div className="empty-state"><p>Belum ada skill aplikasi.</p></div>}</div></section>
    <section className="admin-card"><h2>Konten halaman About</h2><p>Atur profil, label skill, kontak, dan ajakan menuju karya.</p><form action={updateAboutPage} className="form-grid"><label>Judul halaman<input name="eyebrow" defaultValue={about.eyebrow} required /></label><div className="two-columns"><label>Label cerita<input name="story_label" defaultValue={about.story_label} required /></label><label>Judul cerita<input name="story_title" defaultValue={about.story_title} required /></label></div><label>Paragraf tentang kamu<textarea name="story_body" defaultValue={about.story_body} required /></label><label>Paragraf lanjutan<textarea name="story_body_2" defaultValue={about.story_body_2} required /></label><div className="two-columns"><label>Label bagian skill<input name="skills_label" defaultValue={about.skills_label} required /></label><label>Label kontak<input name="links_label" defaultValue={about.links_label} required /></label></div><div className="two-columns"><label>Label CTA<input name="cta_label" defaultValue={about.cta_label} required /></label><label>Judul CTA<input name="cta_title" defaultValue={about.cta_title} required /></label></div><label>Teks tombol CTA<input name="cta_button_label" defaultValue={about.cta_button_label} required /></label><button className="button" type="submit">Simpan halaman About</button></form></section>
    <section className="admin-card"><h2>Konten halaman Projects</h2><p>Atur judul, pembuka, dan catatan penutup halaman Projects.</p><form action={updateProjectsPage} className="form-grid"><div className="two-columns"><label>Label halaman<input name="eyebrow" defaultValue={(projectsPage as ProjectsPage).eyebrow} required /></label><label>Judul halaman<input name="title" defaultValue={(projectsPage as ProjectsPage).title} required /></label></div><label>Lead / pembuka<textarea className="short-textarea" name="lead" defaultValue={(projectsPage as ProjectsPage).lead} required /></label><div className="two-columns"><label>Label catatan<input name="note_label" defaultValue={(projectsPage as ProjectsPage).note_label} required /></label><label>Isi catatan<textarea className="short-textarea" name="note_body" defaultValue={(projectsPage as ProjectsPage).note_body} required /></label></div><button className="button" type="submit">Simpan halaman Projects</button></form></section>
    <section className="admin-card"><h2>Profil & pengaturan website</h2><p>Kontak yang dikosongkan tidak akan ditampilkan di website publik.</p><form action={updateSettings} className="form-grid"><div className="two-columns"><label>Nama<input name="name" defaultValue={site.name} required /></label><label>Lokasi<input name="location" defaultValue={site.location}/></label></div><label>Peran / headline<input name="role" defaultValue={site.role}/></label><label>Bio singkat<textarea className="short-textarea" name="intro" defaultValue={site.intro} required /></label><div className="two-columns"><label>Email publik<input name="email" type="email" defaultValue={site.email}/></label><label>GitHub URL<input name="github_url" type="url" defaultValue={site.github_url}/></label></div><div className="two-columns"><label>Instagram URL<input name="instagram_url" type="url" defaultValue={site.instagram_url}/></label><label>Facebook URL<input name="facebook_url" type="url" defaultValue={site.facebook_url}/></label></div><label>LinkedIn URL<input name="linkedin_url" type="url" defaultValue={site.linkedin_url}/></label><label>Footer<input name="footer" defaultValue={site.footer} required /></label><button className="button" type="submit">Simpan pengaturan</button></form></section>
  </div></AdminShell>;
}
